{% set name = "Orange3-Survival-Analysis" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3914b496efc8abb839595d652e2549ab92d7f5e679a39499161480b85c9986db

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - Orange3
    - lifelines
    - statsmodels
    - pyqt
    - pyqtgraph

test:
  imports:
    - orangecontrib.survival_analysis

about:
  home: http://orange.biolab.si/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Survival Analysis add-on for Orange3 data mining suite
  description: |
    Orange3 Survival Analysis add-on for the Orange3 data mining suite.
  # todo: add when available: doc_url
  dev_url: https://github.com/biolab/orange3-survival-analysis

extra:
  recipe-maintainers:
    - primozgodec
    - markotoplak
    - JakaKokosar
